# ==============================================================================
# USER CONFIGURATION: keybinds.conf
# ==============================================================================
# Add your custom settings for keybinds here.
# These will override or add to the defaults found in ~/.config/hypr/source/keybinds.conf
# This file can also be edited with dusky keybinds manager from the rofi menu or from dusky control center
# ==============================================================================

# -- TERMINAL-CLIPBOARD-START --
unbind = $mainMod, V
bindd = $mainMod, V, Clipboard History, exec, $scripts/clipboard/close_terminal_clipboard.sh uwsm-app -- kitty --class terminal_clipboard.sh -e "$scripts/clipboard/terminal_clipboard.sh"
# -- TERMINAL-CLIPBOARD-END --


# [2026-02-11 20:02] CUST
bindd = $mainMod, [, Lock Screen, exec, uwsm-app -- $scripts/hyprlock/lock.sh




unbind = $mainMod, C




# [2026-02-20 17:21] CUST
unbind = $mainMod, E
bindd = $mainMod, E, File Manager, exec, uwsm-app -- $terminal -e $fileManager


# [2026-02-22 14:33] CUST
unbind = $mainMod, U
bindd = $mainMod, U, Key Press Sound, exec, uwsm-app -- $HOME/user_scripts/wayclick/dusky_wayclick.sh


# [2026-02-22 15:03] CUST
unbind = $mainMod, R
bindd = $mainMod, R, Open Text Editor, exec, uwsm-app -- foot -e $textEditor






# [2026-02-24 00:24] CUST
unbind = $mainMod SHIFT, M
bind = $mainMod SHIFT, M, exec, uwsm-app -- foot -e kew

# [2026-02-27 00:31] UNBIND
unbind = $mainMod, N



# [2026-02-27 22:36] CUST
bindd = $mainMod, Return, Launch Terminal, exec, uwsm-app -- $terminal

# [2026-02-27 22:43] NEW
bindd = $mainMod, Q, Close Window, killactive,


# eg, for reference:
# bind = $mainMod, period, layoutmsg, move +col
# bind = $mainMod, comma, layoutmsg, move -col
bind = $mainMod SHIFT, period, layoutmsg, movewindowto r
bind = $mainMod SHIFT, comma, layoutmsg, movewindowto l
bind = $mainMod SHIFT, up, layoutmsg, movewindowto u
bind = $mainMod SHIFT, down, layoutmsg, movewindowto d
# --- END PLUGIN: scrolling ---
# --- END PLUGIN: expo ---
# [2026-02-27 23:36] CUST
bindd = $mainMod, bracketleft, hyprscrolling layoutmsg +, layoutmsg, move +col

# [2026-02-27 23:59] CUST
bindd = $mainMod, bracketright, hyprscrolling layoutmsg -, layoutmsg, move -col

# [2026-02-28 00:14] NEW
bind = $mainMod ALT, l, exec, hyprctl getoption general:layout | grep -q 'dwindle' && hyprctl keyword general:layout scrolling || hyprctl keyword general:layout dwindle


# [2026-03-01 21:40] NEW
unbind = $mainMod, B
bindd = $mainMod, B, Launch Browser, exec, uwsm-app -- helium-browser

# Auto-generated by Browser Switcher
bindd = $mainMod, W, Launch Browser, exec, uwsm-app -- $browser



# [2026-03-09 00:49] NEW
bind = SUPER SHIFT, W, exec, killall -SIGUSR2 waybar
