# ==============================================================================
# USER CONFIGURATION: plugins.conf
# ==============================================================================
# Add your custom settings for plugins here.
# These will override or add to the defaults found in ~/.config/hypr/source/plugins.conf
# ==============================================================================


# --- BEGIN PLUGIN: scrolling ---
plugin {
    hyprscrolling {
        column_width = 0.979
        focus_fit_method = 3
    }
}
# --- END PLUGIN: scrolling ---

# --- BEGIN PLUGIN: expo ---
plugin {
    hyprexpo {
        columns = 4
        gap_size = 7
        bg_col = rgb(111111)
        workspace_method = center current
    }
}
# --- END PLUGIN: expo ---
