# -----------------------------------------------------
# Helium
windowrule {
    name = helium
    match:class = ^(helium)$
    # match:title = ^(helium)$
    float = off
    # pin = on
    size = 1352 731
    # size = (monitor_w*0.9898) (monitor_h*0.9518)
    move = 7 30
    # move = (monitor_w*0.0051) (monitor_h*0.0391)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    # opacity = 0.9 0.9
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    # no_blur = on
    # no_shadow = on
    # no_dim = on
    # opaque = on
    # dim_around = on

    # --- Placement ---
     workspace = 2
    #  monitor = DP-1
}

# -----------------------------------------------------
# foot
windowrule {
    name = foot
    match:class = ^(foot)$
    # match:title = ^(foot)$
    float = off
    # pin = on
    size = 1352 731
    # size = (monitor_w*0.9898) (monitor_h*0.9518)
    move = 7 30
    # move = (monitor_w*0.0051) (monitor_h*0.0391)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    # opacity = 0.9 0.9
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    # no_blur = on
    # no_shadow = on
    # no_dim = on
    # opaque = on
    # dim_around = on

    # --- Placement ---
     workspace = 1
    # monitor = DP-1
}

# -----------------------------------------------------
# I Wanna Be Yours
windowrule {
    name = kew
    match:class = ^(kew)$
    # match:title = ^(I Wanna Be Yours)$
    float = on
    # pin = on
    size = 362 489
    # size = (monitor_w*0.2650) (monitor_h*0.6367)
    move = 980 45
    # move = (monitor_w*0.7174) (monitor_h*0.0586)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    # opacity = 0.9 0.9
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    # no_blur = on
    # no_shadow = on
    # no_dim = on
    # opaque = on
    # dim_around = on

    # --- Placement ---
     workspace = 5
    # monitor = DP-1
}


# -----------------------------------------------------
#Thunar
windowrule {
    name = thunar
    match:class = ^(thunar)$
    # match:title = ^(ishfar - Thunar)$
    float = off
    # pin = on
    size = 1352 731
    # size = (monitor_w*0.9898) (monitor_h*0.9518)
    move = 7 30
    # move = (monitor_w*0.0051) (monitor_h*0.0391)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    # opacity = 0.9 0.9
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    # no_blur = on
    # no_shadow = on
    # no_dim = on
    # opaque = on
    # dim_around = on

    # --- Placement ---
     workspace = 3
    # monitor = DP-1
}

# -----------------------------------------------------
# Prism Launcher 10.0.5
windowrule {
    name = orgprismlauncherPrismLauncher
    match:class = ^(org\.prismlauncher\.PrismLauncher)$
    # match:title = ^(Prism Launcher 10\.0\.5)$
    float = off
    # pin = on
    size = 1352 731
    # size = (monitor_w*0.9898) (monitor_h*0.9518)
    move = 7 30
    # move = (monitor_w*0.0051) (monitor_h*0.0391)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    # opacity = 0.9 0.9
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    # no_blur = on
    # no_shadow = on
    # no_dim = on
    # opaque = on
    # dim_around = on

    # --- Placement ---
     workspace = 4
    # monitor = DP-1
}

